version: '3.7'
services:
#  frontend:
#    build:
#      context: ./catalog_frontend
#      dockerfile: Dockerfile
#    depends_on:
#      - backend

  backend:
    build:
      context: ./catalog_backend
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:11.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data: