version: '3.7'

services:
  frontend:
    build:
      context: ./catalog_frontend
      dockerfile: Dockerfile
    image: catalog-frontend
    ports:
      - 80:80
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - backend

  backend:
    build:
      context: ./catalog_backend
      dockerfile: Dockerfile
    image: catalog-backend
    ports:
      - 8000:8000
    #restart: always
    depends_on:
      - database

  database:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=django
## I know this isn't cool. Need to find a better way to set password ##
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=catalog
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pg_conf:/docker-entrypoint-initdb.d/
    #restart: always

volumes:
  postgres_data: