# Generated by Django 2.2.1 on 2019-08-07 21:05
import os
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = []

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = os.environ.get("DJANGO_SU_NAME")
        DJANGO_SU_EMAIL = os.environ.get("DJANGO_SU_EMAIL")
        DJANGO_SU_PASSWORD = os.environ.get("DJANGO_SU_PASSWORD")

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME, email=DJANGO_SU_EMAIL, password=DJANGO_SU_PASSWORD
        )

        superuser.save()

    operations = [migrations.RunPython(generate_superuser), 
                    migrations.RunSQL("ALTER SYSTEM SET log_connections = True;", ""),
                    migrations.RunSQL("ALTER SYSTEM SET log_disconnections = True;", ""),
                    migrations.RunSQL("ALTER SYSTEM SET log_timezone = 'US/Central';", "")]
