# Generated by Django 2.2.1 on 2019-08-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, unique=True)),
                ('associated_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.CarMake')),
            ],
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=50)),
                ('date_added', models.DateField()),
                ('color', models.CharField(blank=True, max_length=20)),
                ('part_description', models.TextField(blank=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.CarMake')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='PartPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_picture', models.BinaryField()),
                ('car_part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_api.CarPart')),
            ],
        ),
    ]
