# Generated by Django 3.1.2 on 2020-10-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.UUIDField(default='7740502a', editable=False, primary_key=True, serialize=False)),
                ('make_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default='f5386a21', editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=50)),
                ('part_description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default='c46824f8', editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('make_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.make')),
            ],
        ),
    ]
